### ISSUE TITLE
Some ITIS sql queries not working

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#404]
* `getanymatchcount()` - tsn type is working but string input doesn't work
* `getfullhierarchyfromtsn()` - use stored procedures - see the `taxize_sql` repo for the scripts  - SQLite I believe doesn't support these stored scripts, so perhaps move ITIS to using PostgreSQL insteead?
* `getitistermsfromcommonname()` not working
* `getpublicationsfromtsn()` compare  `getpublicationsfromtsn(70340, "api")` to `getpublicationsfromtsn(70340, "local")`, local result has much more data, no bueno
* `getitistermsfromcommonname(x="buya")` doens't return any matches but shuld

**Comment by DaliaAConde** [comment]
Hi for the function tax_name: it works in ncb but not on itis database
tax_name(query = "Acrocephalus aedon", get = "family", db = "ncb")
tax_name(query = "Acrocephalus aedon", get = "order", db = "itis")

However it retreives the taxonomy of the species with the function
out <- get_ids(names = "Acrocephalus aedon", db = c("itis"))
out <- classification(out)

It will be great if it is possible to do it directly with tax_name function since you can then retrieve only one taxonomic level.

**Comment by sckott** [comment]
@DaliaAConde can you open this in a new issue?  since i don't think it's related to this issue. Then I'll answer you there.

**Comment by sckott** [comment]
closing, working on `ropenscilabs/taxizedb`
