### ISSUE TITLE
Algaebase #newdatasource

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/taxize#433]
http://www.algaebase.org/

**Comment by sckott** [comment]
Nice one. 

@jebyrnes do you know if they have any web services, either an API, dumps, or allow html scraping? I looked around but don't see anything 

One solution is that Algaebase is available via Worms (e.g., http://www.marinespecies.org/aphia.php?p=taxdetails&id=145821) so you could use `taxizesoap` to get at Algaebaes data. Note that `taxizesoap` won't work on R 3.2 or greater due to a change in the base R code that makes a dependency `XMLschema` not operate correctly. It's a mess. but should work on R < 3.2

I'm worker on a stop-gap solution that will allow worms/pesi/mycobank to feed into the main `taxize` package, but it's not quite ready yet.

**Comment by jebyrnes** [comment]
I don't - however, their taxonomy IS available via EOL (you can look at the methods in REOL, which I regularly use to access algaebase). So that could be a workaround.

(this also makes me wonder about fishbase...)

**Comment by sckott** [comment]
> (this also makes me wonder about fishbase...)

I wonder how fresh the data is that EOL has from Algaebase. I imagine there's some lag time between when Algaebase has new data and when EOL gets it. 

you mean getting any fishbase data, or specifically the fishbase names data?  If all data, carl is working on a new rfishbase client https://github.com/ropensci/rfishbase that works with a new API we've built

**Comment by jsta** [comment]
I think that algaebase may be off the table as far as a taxize datasource. I made an inquiry to the proprietor who told me that they are planning to release a paid access api to licensees. Any attempt to scrape data by automated means would result in legal action.

**Comment by sckott** [comment]
yikes, sounds like they are keeping their legos to themselves

**Comment by sckott** [comment]
closing, seems won't happen
