### ISSUE TITLE
Flora do Brasil 

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#442]
http://floradobrasil.jbrj.gov.br

Suggested by @gustavobio - can use via his `flora` package https://github.com/gustavobio/flora

Just use the taxonomic data here

**Comment by sckott** [comment]
link http://ipt.jbrj.gov.br/jbrj/resource?r=lista_especies_flora_brasil

**Comment by gustavobio** [comment]
The checklist is also available on GBIF: 

http://www.gbif.org/dataset/aacd816d-662c-49d2-ad1a-97e66e2a2908

Looks like the API isn't matching names against this dataset though:

http://api.gbif.org/v1/species?name=Myrcia%20guianensis

**Comment by sckott** [comment]
thanks @gustavobio - where is the best place to get this data from?  your pkg, GBIF, or http://www.plantminer.com/flora

**Comment by gustavobio** [comment]
Probably best to get it from http://ipt.jbrj.gov.br/jbrj/resource?r=lista_especies_flora_brasil if you want to have full control of updates. They publish a new dataset weekly, but since there is no change log available I don't really know the extent of the changes between db dumps. I update flora with new data once every three months or so and never had a complaint about inaccurate results or missing species.

If you follow this route, there is a minimal amount of translating from Portuguese involved though . All fields, including name status, are in Portuguese. I can help you with that. There are also some inconsistencies such as duplicate entries, synonyms with no accepted names, and so on that I try to solve programatically. If not having the latest dataset isn't an issue, I'd probably just grab the data from flora or build wrappers for the functions in it.

**Comment by sckott** [comment]
Thanks for the feedback. Sounds like best option is to get directly from that link
