### ISSUE TITLE
skip tests if servers are down

### ISSUE THREAD

**Issue by EDiLD** [ropensci/taxize#455]
Some tests may fail, if the server is down.
This always annoyed  me.

What I am currently trying in my webchem package is to skip tests if the server is down.
See https://github.com/ropensci/webchem/blob/master/tests/testthat/test-physprop.R.

Also something for taxize?

**Comment by sckott** [comment]
@EDiLD hmmm, maybe, but the main functionality of most fxns here is to hit a web API, so if it's down then it will be down for a user

In a perfect world, in every function that works with a web API, we'd separate the API call from the downstream processing of the result. However, we don't have that separation right now AFAIK for any functions here. 

Once we have the separation, then we could write tests for the API call part and separately for the downstream processing part, and skip API call tests for services that are down.  

It would take some work since we have so many functions, but do you want to work towards this?

**Comment by EDiLD** [comment]
No, it wont be on top of my todolist...
