### ISSUE TITLE
Index Fungorum

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#471]
I think it's available via PESI -e.g., http://www.eu-nomen.eu/portal/taxon.php?GUID=urn:lsid:indexfungorum.org:names:17703  so in new integration with EU API, we may be all set #466 

__OR__

looks like they may have a REST interface in addition to SOAP, e.g, http://www.indexfungorum.org/ixfwebservice/fungus.asmx/NameSearch?SearchText=Gymnopus&AnywhereInText=true&MaxNumber=2

**Comment by sckott** [comment]
see also ropensci/taxizesoap#4

**Comment by sckott** [comment]
@vinsondoyle @MRittinghouse Okay, i found that IndexFungorum has an interface I can use in `taxize` package, so there's now a suite of functions there, draft format, but useable, The outputs are kinda messy since there's lots of fields they return that I haven't looked through yet what to return and what not to return. Any ideas welcome. 

See functions starting with `fg_*()`

There's a suite of methods they allow to request data, that don't seem to work for me so far, a list of what's happened so far (`NO` meaning I haven't done it yet):

* AllUpdatedNames - YES
* AuthorSearch - YES
* AuthorSearchDs - NO
* DeprecatedNames - YES
* DeprecatedNamesByRank - NO
* EpithetSearch - YES
* EpithetSearchDs - NO
* IsAlive - YES
* NameByKey - YES
* NameByKeyDs - NO
* NameByKeyRDF - NO
* NameFullByKey - YES
* NameSearch - YES
* NameSearchDs - NO
* NamesByCurrentKey - NO
* NamesByCurrentKeyDs - NO
* NewNames - NO
* NewNamesInRange - NO
* UpdatedNames - NO
* UpdatedNamesInRange - NO

Any feedback much appreciated

**Comment by vinsondoyle** [comment]
You are not kidding. The output is indeed messy, with much extraneous information (for me) in the couple queries that I have submitted. At first glance, it appears that the information I would most like to be able to access, the taxonomic hierarchy for a given taxon, is not available directly. However, I see that I can do this with fg_name_by_key(), once I find the key with fg_epithet_search().

In general, the most useful information is the protolog info (journal, issue, page numbers, etc), link to the protolog (often scanned .jpg from librifungorum), current name, authors, and taxonomic hierarchy.

I will keep testing it out as I am able.

**Comment by sckott** [comment]
thanks for the feedback @vinsondoyle 

> it appears that the information I would most like to be able to access, the taxonomic hierarchy for a given taxon, is not available directly

Assuming things go smoothly, I can wrap these fxns into the higher level taxize functions to retrieve hierarchies, get children, etc. Not promising, but hopefully 

What method gives protolog?

**Comment by vinsondoyle** [comment]
fg_name_by_key() returns the complete protolog info. The link to the scanned image is actually of Saccardo's Sylloge Fungorum rather than the actual protolog.

In the example below: 
The url links to the scanned Sylloge Fungorum. The published list reference is where this taxon is listed in an other volume of Sylloge Fungorum. The "VOLUME PAGE YEAR_x0020_OF_x0020_PUBLICATION, actually refers to the protolog. The journal of the protolog is listed below (pubOriginalTitle). Pretty jumbled, but it is all there. fg_epithet_search() returns only partial protolog info.

Example:
fg_name_by_key("178511")

returns (in addition to much else which I have excluded):
NAME_x0020_OF_x0020_FUNGUS        AUTHORS
Colletotrichum rhexiae      Ellis & Everh.

PUBLISHED_x0020_LIST_x0020_REFERENCE
Saccardo's Syll. fung. XI: 570; XII: 121

VOLUME PAGE YEAR_x0020_OF_x0020_PUBLICATION
    46  372                            1894

$Ihttp://www.librifungorum.org/Image.asp?ItemID=71&ImageFileName=SyllogeFungorum11-570.jpg

pubOriginalTitle
Proceedings of the Academy of Natural Sciences of Philadelphia

**Comment by sckott** [comment]
@vinsondoyle Do you thin any columns from the outputs of these functions can be dropped?  I'm not really familiar with this data.

**Comment by vinsondoyle** [comment]
I will take a closer look.

**Comment by sckott** [comment]
@vinsondoyle I see no way of getting a taxonomic hierarchy from index fungorum, do you?

**Comment by sckott** [comment]
good enough for now, open issues as needed for improvements
