### ISSUE TITLE
iucn_summary improvements

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#472]
the IUCN api is super slow 

e.g. try http://api.iucnredlist.org/go/panthera-uncia

That makes `iucn_summary()` super slow, then also `iucn_getname()` slow, which uses the former function

I think we can use GNR resolver for `iucn_getname()` making it less slow, but not sure how to fix `iucn_summary()`

**Comment by rossmounce** [comment]
Do you not use the newer IUCN API for a reason? Thought I'd mention it just in case. Is it because it requires a key / not open?

http://apiv3.iucnredlist.org/

**Comment by sckott** [comment]
Thanks, didn't know about it, will probably use it

**Comment by rossmounce** [comment]
Brill! Aside from requiring a token and the hilariously restrictive terms and conditions it seems quite good to me.

http://www.iucnredlist.org/info/terms-of-use#4._No_reposting__sublicensing_and_or_redistribution "You may not repost, or redistribute to any third party, the IUCN Red List Data in whole, or in part, by any means, including... except as may otherwise be expressly permitted by IUCN ***in writing***"  I'm surprised they didnt specify the colour of ink required. Black or Blue?

**Comment by sckott** [comment]
yeah, the licensing bit is odd, not good

**Comment by sckott** [comment]
using new red list API now #492 closing
