### ISSUE TITLE
get_eolid don't use param. key and returns wrong link

### ISSUE THREAD

**Issue by Markus2015** [ropensci/taxize#484]
I think that there are two bugs in function get_eolid (I'm using ‘taxize’ version 0.6.8.9320)

example:
`get_eolid('Malus domestica',key='*********************************')`

1.) if I provide the key from my EOL account, I'll get the message
`Using default key: Please get your own API key at http://eol.org/users/register`

2.) for this example we have more than one result so we can see that EOL has two id's: a pageid and the eolid - attr(,"uri") should return the link with the pageid! (not eolid - as that one is not valid)

wrong:
`attr(,"uri")
[1] "http://eol.org/pages/57278800/overview"`

valid link with pageid:
`http://eol.org/pages/629094/overview`

Regards Markus

**Comment by sckott** [comment]
thanks @Markus2015 looking into it

**Comment by sckott** [comment]
first of all, EOL is a special snowflake, as they have page IDs for each taxon, but then within that, they have taxon ids for various taxa within that page (e.g., GBIF and NCBI each have a taxon they refer to within the page [i.e., taxon]). And we need the taxon ids from a particular data provider (e.g, NCBI) to do other things, like get a higher classification tree, __NOT THE PAGE ID__

However, humans want the page id, not the taxon id

So I'm trying to fix the output so that the URI provided is for the page, not the taxon id, so the URI actually works. but the id returned will remain the same, as it's used downstream

**Comment by sckott** [comment]
@Markus2015 reinstall from github

keys should be used now that are passed in

and the URI returned should always be with the pageid so they should go to the right place in a browser - the id that is returned is unchanged, as we use that downstream to  do other things, 

let me know if it works now

**Comment by Markus2015** [comment]
Thank you very much for the fast answer and perfect solution! 
I can confirm that both issues are solved, regards Markus

**Comment by sckott** [comment]
great, glad it works.
