### ISSUE TITLE
Additional options for IUCN summary

### ISSUE THREAD

**Issue by pmarchand1** [ropensci/taxize#493]
I have been making custom adjustments to `iucn_summary` for some applications and was wondering if they would be useful in the package:
1) get iucn_summary by iucn_id instead of by name (this was useful for some taxa where the `iucn_summary` failed, but I could successfully run `iucn_id`)
2) separate the 'native' and 'introduced' countries in the distribution

I'm happy to submit code in a pull request, but wanted to check if there's a good reason not to implement these options or if this function is on hold pending possible API changes.

**Comment by sckott** [comment]
Thanks @pmarchand1 for the offer to share your changes. 

I think I'd like to see what happens with the IUCN API, see #492 before we do this because all IUCN interfaces could change - Hopefully we won't break current functions in the pkg to not break people's code that use `taxize`, but we can always add new functions

So I'll get back to you after I see how new API will work

**Comment by sckott** [comment]
https://github.com/ropenscilabs/rredlist started pkg for the new API, i'll get that to CRAN soon, then start incorporating into this pkg - then we can revisit your changes

**Comment by sckott** [comment]
@pmarchand1 Okay, we've included use of the new `rredlist` package that uses the new IUCN - `iucn_summary` is changed a bit, using the new API and the old API

Please do submit the pull request

**Comment by pmarchand1** [comment]
@sckott I just submitted the pull request #502

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
closed via #503
