### ISSUE TITLE
tax_name throwing errors when trying to query certain names

### ISSUE THREAD

**Issue by daattali** [ropensci/taxize#542]
Discovered by @keshiniD: certain higher-order queries throw an error

```
Error in `$<-.data.frame`(`*tmp*`, "rank", value = character(0)) : 
  replacement has 0 rows, data has 1
```

For example:

```
tax_name(query = "root", get = "family", db = "ncbi")
```

or "viruses"

**Comment by daattali** [comment]
It's probably not a common use case, it came up from using the result of
ncbi_get_taxon_summary

**Comment by sckott** [comment]
thanks, actually a bug in `classificaiton()` called internally

**Comment by sckott** [comment]
So: 

`viruses` are in NCBI when you search in the web portal http://www.ncbi.nlm.nih.gov/taxonomy/?term=viruses but there's no taxonomic classification data when you query on it's NCBI taxon ID http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=taxonomy&ID=10239 - compared to http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=taxonomy&ID=9606 where taxonomic classification data  is given (see the `LineageEx ` node)

same with `root`, no taxonomic classification data

im pushing changes so that `classification()` gives back `NA` when no taxonomic classification data is found, and `tax_name()` gives back a 0 row data.frame, cause we want to make it easy for users to pass in many names to the fxn, so no results give empty data.frame back

**Comment by sckott** [comment]
@daattali reinstall `devtools::install_github("ropensci/taxize")`

**Comment by daattali** [comment]
Seems fixed, thanks!
