### ISSUE TITLE
handling no name matches vs multiple name matches with classification() in a loop

### ISSUE THREAD

**Issue by ahhurlbert** [ropensci/taxize#547]
I'm trying to clean a vector of taxonomic names obtained from someone else's dataset.

These names reflect entities of varying taxonomic level, and occasionally include strings that aren't expected to match anything (e.g., "Helianthus sp. A") while others might have multiple entries which invoke the interactive taxize feature.

However, I'm trying to automate the cleaning of these 600 names without invoking the interactive feature. Here's my own hacky wrapper code around `classification()` to give you a sense of what I'm trying in order to pull out higher order names if there are any and store them in a format useful to me:

```
getTaxRanks = function(name) {
  classif = classification(name, db = 'itis')
  names(classif) = 'tax'
  
  if(is.null(nrow(classif$tax))) {
    phy = cla = ord = fam = gen = NA
  } else {
    phy = classif$tax$name[classif$tax$rank == 'Phylum']
    cla = classif$tax$name[classif$tax$rank == 'Class']
    ord = classif$tax$name[classif$tax$rank == 'Order']
    fam = classif$tax$name[classif$tax$rank == 'Family']
    gen = classif$tax$name[classif$tax$rank == 'Genus']
    
    if (length(phy) == 0) { phy = NA }
    if (length(cla) == 0) { cla = NA }
    if (length(ord) == 0) { ord = NA }
    if (length(fam) == 0) { fam = NA }
    if (length(gen) == 0) { gen = NA }
  }
  
  taxranks = list(originalName = name, 
                  phylum = phy, 
                  class = cla, 
                  order = ord, 
                  family = fam, 
                  genus = gen)
  return(taxranks)
}
```

For names with multiple matches, as a first pass I would be happy to try just setting the argument `rows = 1` (and ideally saving a flag somewhere that there were multiple matches so I might want to look into this record individually). However, if I add this argument to the `classification` function when the name doesn't match anything in the database, the function returns an error, e.g.: 
```
> classification("asdf", db = "itis", rows = 1)

Retrieving data for taxon 'asdf'

Error in x[rows, ] : incorrect number of dimensions
```

So here is a test vector that includes a "good" name, a "bad" name, and a name with multiple matches:
`spp = c('Pisidium', 'Orthocladiinae a', 'Clinocera')`

Is there a simple tweak you can recommend to my `getTaxRanks` function above that will allow this for loop to run to completion, grabbing the first row in the case of multiple matches?

```
sppranks = c()
for (s in spp) {
  ranks = getTaxRanks(s)
  sppranks = rbind(sppranks, ranks)
}
sppranks = data.frame(sppranks, row.names = NULL)
```

Thanks for any insight!

**Comment by sckott** [comment]
Thanks for the issue and the code to replicate the problem. As you can see above, I opened an issue to fix that bug with the `rows` param when no match found. 

> For names with multiple matches, as a first pass I would be happy to try just setting the argument rows = 1 (and ideally saving a flag somewhere that there were multiple matches so I might want to look into this record individually)

unfortunately, as is currently, `classificatuon()` doesn't tell you that there was multiple matches anywhere in the return object if you use `rows` to get back just 1 record. We can of course do that, by putting another attribute in the output object. Right now there's one extra attribute (`db` for which data source was queried):

```r
x <- classification('Poa annua', db = 'tropicos', rows = 2)
attributes(x)
#> $names
#> [1] "Poa annua"
#> 
#> $class
#> [1] "classification"
#> 
#> $db
#> [1] "tropicos"
```

We can add another attribute for whether there was more than 1 match, regardless of `rows` usage

There's a few approaches you can use: 

* If you pass in taxonomic names to `classification()`, it uses `get_*()` (e.g., `get_tsn` for ITIS)  to first get the right taxonomic serial number. You can use `get_tsn` e..g, like `get_tsn('Clinocera', accepted = TRUE)` to get back only accepted/valid names. `accepted` is set to `FALSE` by default. And you can pass on `accepted` param to `get_tsn` with your `classification` like `classification('Clinocera', db = "itis", accepted = TRUE)`. With this taxon you get back only 1 result after you limit to accepted names only because after that we look for any exact matches. That won't work in all cases of course since some names will result in multiple matches even after limiting to accepted names. 
* All `get_*()` functions have another version like `get_*_()` with an underscore at the end. The underscore version is specifically for getting all the data, so no interactive prompt will be displayed, but you can still use other params also in the non-underscore version of the function. You can use the underscore version to grab names/ids, then do whatever you like to sieve that bunch, then pass to classification. 

I opened an issue to get a vignette done specifically dealing with programmatic name cleaning issue since it's such a common one - and important to get right https://github.com/ropensci/taxize/issues/549

**Comment by ahhurlbert** [comment]
Thanks @sckott, that helps.

A name cleaning vignette will be very helpful!

**Comment by sckott** [comment]
Glad it helps, don't hesitate to ask more questions about this issue or anything else
