### ISSUE TITLE
downstream for higher taxa available in IUCN

### ISSUE THREAD

**Issue by diogoprov** [ropensci/taxize#578]
I noticed that all functions that interact with ID databases don't work with IUCN. I'd like to retrieve the species list with polygons available in IUCN, how can I do that in taxize?
Thank you

**Comment by sckott** [comment]
thx for your question. Im a bit confused

> I'd like to retrieve the species list with polygons available in IUCN

this is a separate request from downstream, correct?  And you are referring to the `downstream()` function, correct? `downstream` gets all taxa for a certain rank downstream of a target taxon. 

While the polygon thing is I assume is a spatial polygon, correct? That isn't supported in taxize

**Comment by diogoprov** [comment]
Hi @sckott , thanks for the quick reply. Sorry, I didn't make my question clear enough. I'm referring to the `downstream()` function indeed. I just wanted to know if it'd be possible to get, for ex., all taxa for Anura that are in the IUCN website, like the other databases

**Comment by sckott** [comment]
thanks @diogoprov 

There's no concept AFAIK in the redlist API of fuzzy searching by taxon name. I just emailed the API maintainer about this. The ability to fuzzy search by name is important if we want to have the same behavior that other taxon databases have - to keep interfaces consistent. 

however, once you have a taxon ID , then the other taxize functions are in theory useable

So we could add IUCN support - for a `get_*` function i guess we'd just have it wrap `rredlist::rl_search`, which requires an exact taxon name (the search part is misleading I guess) - that would allow to get the IUCN ID, then you can pass that down to other fxns.

possible ID supported fxns with IUCN

- [ ] `synonyms()`
- [ ] `sci2comm()`
- [ ] `comm2sci()`

not possible: `downstream`, `classification`, `children`, `upstream`, `lowest_common` - Because IUCN doesn't share their taxonomy - so there's no way to get a taxonomic classification, tax. children, etc. 

There is

```
t(rredlist::rl_search('Fratercula arctica')$result)
```

```
taxonid            "22694927"                
scientific_name    "Fratercula arctica"      
kingdom            "ANIMALIA"                
phylum             "CHORDATA"                
class              "AVES"                    
order              "CHARADRIIFORMES"         
family             "ALCIDAE"                 
genus              "Fratercula"              
main_common_name   "Atlantic Puffin"         
authority          "(Linnaeus, 1758)"        
published_year     "2016"                    
category           "VU"                      
criteria           "A4abcde"                 
marine_system      "TRUE"                    
freshwater_system  "FALSE"                   
terrestrial_system "TRUE"                    
assessor           "BirdLife International"  
reviewer           "Butchart, S. & Symes, A."
aoo_km2            NA                        
eoo_km2            "20800000"                
errata_flag        "FALSE"                   
errata_reason      NA  
```

which gives some higher taxon names, but no IDs for those names, which would make inconsistent with other data sources

**Comment by diogoprov** [comment]
humm... I see, thanks for clarifying that. Indeed, they don't make their taxonomy of choice explicit either, so that's another problem that should be addressed in the database.

**Comment by sckott** [comment]
I don't think they will expose the taxonomy though, but you never know

**Comment by sckott** [comment]
Heard back from IUCN and there's no way to do fuzzy search - so I'll play around with this and see if it makes sense to have `get_iucn` since there's no real search like there is for other data sources  - one option is to use some other API to search on IUCN names - as some other sources have IUCN data but I don't know how up to date those are

**Comment by diogoprov** [comment]
ok, thanks @sckott !!

**Comment by sckott** [comment]
sorry, sorta dropped off my list, will get to asap

**Comment by diogoprov** [comment]
Hi @sckott ! Thanks for working on that. 
I have tried [very quickly] the new function, but I think I'm doing sth wrong. 

![sem titulo](https://user-images.githubusercontent.com/5214836/27642642-6c7ca2ec-5bed-11e7-9ff4-0961893a08d0.jpeg)

I'll give it a try once again later.

**Comment by sckott** [comment]
@diogoprov that image didn't come through, thoughts?
