### ISSUE TITLE
error retrieving species from genbank IDs in bulk

### ISSUE THREAD

**Issue by afkoeppel** [ropensci/taxize#666]
Hello,

I'm attempting to use taxize to get the taxonomy (specifically species) from a large number of genbank IDs generated from a BLAST search.  The package seems to be working well for individual genbank IDs, but when I try to scale up to the complete list things appear to be breaking down.

My first attempt used purr:map to try to get the species assignments, but I thought the problem might be with too many API calls at once, so I switched to a for-loop with a Sys.sleep(0.5) built in.  That seemed to help at first, but the loop eventually crashed with a similar error.

Session info an R code are below.  All error messages received are included with the code.

Any assistance/advice would be greatly appreciated.

Thanks,

Alex Koeppel

<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] bindrcpp_0.2    forcats_0.2.0   stringr_1.2.0   purrr_0.2.4    
 [5] readr_1.1.1     tidyr_0.7.2     tibble_1.3.4    ggplot2_2.2.1  
 [9] tidyverse_1.2.1 taxize_0.9.0    dplyr_0.7.4     Tmisc_0.1.17   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14        cellranger_1.1.0    plyr_1.8.4         
 [4] bindr_0.1           iterators_1.0.9     tools_3.3.2        
 [7] lubridate_1.7.1     gtable_0.2.0        jsonlite_1.5       
[10] nlme_3.1-131        lattice_0.20-35     pkgconfig_2.0.1    
[13] rlang_0.1.6         psych_1.7.8         foreach_1.4.4      
[16] cli_1.0.0           rstudioapi_0.7      crul_0.5.0         
[19] curl_3.1            parallel_3.3.2      haven_1.1.0        
[22] httr_1.3.1          xml2_1.1.1          hms_0.4.1          
[25] grid_3.3.2          reshape_0.8.7       glue_1.2.0         
[28] data.table_1.10.4-3 R6_2.2.2            readxl_1.0.0       
[31] foreign_0.8-69      modelr_0.1.1        reshape2_1.4.3     
[34] magrittr_1.5        scales_0.5.0        codetools_0.2-15   
[37] rvest_0.3.2         assertthat_0.2.0    bold_0.5.0         
[40] mnormt_1.5-5        colorspace_1.3-2    ape_5.0            
[43] stringi_1.1.6       lazyeval_0.2.1      munsell_0.4.3      
[46] broom_0.4.3         crayon_1.3.4        audio_0.1-5 </strong></summary>
```
</details>

My code:

```r
#Load modules
library(Tmisc)
library(dplyr)
library(taxize)
library(tidyverse)

#Read in blast results
blast.res <- read.table("PE1003145_singlehit_ids.txt", sep='\t')
colnames(blast.res)<-c("read","gi","gb")

#Function to Covert GI ID to species taxonomy.
get_species <- function(giid){
  taxid <- genbank2uid(id = giid, batch_size=1)[1]
  #taxid <- genbank2uid(id = giid)[1]
  if(is.na(taxid)){
    return("NA")
  } else {
    tax.class <- classification(taxid, db="ncbi")[[1]] %>% 
    filter(rank=="species") %>% select(name)
    tax.spec <- tax.class[1] %>% as.character()
    return(tax.spec)}
  }

#Test function
get_species("3135380")
#[1] "Campylobacter hominis"
get_species("193075745")
#[1] "Campylobacter hominis"
get_species("399187008")
#[1] "uncultured bacterium"

#Test function on a subset
#blast.test <- blast.res[1:20,]
#blast.test <- blast.res[1:500,]

#Apply Function to all IDs in blast table.
#new.col <- blast.test$gi %>% 
new.col <- blast.res$gi %>% 
  as.character() %>%
  map(~as_tibble(.)) %>%
  map(~get_species(giid=.)) %>%
  unlist()
#Error in UseMethod("filter_") : 
#  no applicable method for 'filter_' applied to an object of class "logical"
#In addition: There were 20 warnings (use warnings() to see them)
warnings() %>% head(3)
#Warning messages:
#1: In genbank2uid(id = giid, batch_size = 1) :
#  An error occurred looking up taxon ID(s).
#2: In genbank2uid(id = giid, batch_size = 1) :
#  An error occurred looking up taxon ID(s).
#3: In genbank2uid(id = giid, batch_size = 1) :
#  An error occurred looking up taxon ID(s).

#The above using map is failing. Trying for-loop
new.col<-vector()
for(x in 1:length(blast.res$gi)){
  #x.gi <- blast.test$gi[x] %>% as.character()
  x.gi <- blast.res$gi[x] %>% as.character()
  xspec <- get_species(x.gi)
  new.col <- c(new.col, xspec)
  Sys.sleep(0.5)
}
#The above loop was able to retrieve species for ~2000 gb IDs, but then failed with the error below.

#Error in curl::curl_fetch_memory(url, handle = handle) : 
#  Timeout was reached: Connection timed out after 10000 milliseconds
#In addition: There were 31 warnings (use warnings() to see them)
warnings() %>% head(3)
#Warning messages:
#1: In genbank2uid(id = giid, batch_size = 1) :
#  An error occurred looking up taxon ID(s).
#2: In genbank2uid(id = giid, batch_size = 1) :
#  An error occurred looking up taxon ID(s).
#3: In genbank2uid(id = giid, batch_size = 1) :
#  An error occurred looking up taxon ID(s).
```

**Comment by sckott** [comment]
thanks for this @afkoeppel !

First, package version. I did send a new version of `taxize` to cran two weeks ago, but they have not accepted it yet. You can in general get dev versions like `remotes::install_github("ropensci/taxize")` or `install.packages("taxize", repos = "http://packages.ropensci.org")` - That new version `>= v0.9.2` has new features of integrating your NCBI API key. This is a newish thing that NCBI does. If you use your API key you get a higher rate limit. 

Second, although we integrated the API key usage throughout most of the pkg, I actually missed it in `genbank2uid` - I just pushed a fix for that function, so to install do `remotes::install_github("ropensci/taxize")` and let me know if. you still have the same problems or if it's any better

Some other things:

### rate limits

Here's the info on Entrez's rate limits and API keys (that's also in the package docs, see `?taxize-authentication`):

> E-utils users are allowed 3 requests/second without an API key. Create an API key (in your account at  https://www.ncbi.nlm.nih.gov/account/) to increase your e-utils limit to 10 requests/second. Contact our help department (eutilities@ncbi.nlm.nih.gov) if you need higher throughput. Only one API Key per user. Replacing or  deleting will inactivate the current key. Refer to documentation   (https://www.ncbi.nlm.nih.gov/books/NBK25497/) for more.

### those pesky timeout errors

Some web APIs error from time to time, probably because they get under heavy load and mess up some requests, NCBI is one of these, they often have errors. So one approach to dealing with it is something like `tryCatch` where you run a function, and if it errors, you can even match on the timeout error, then do x and if it doesn't error do y. 

### A different approach for lots of data

We have a sister package `taxizedb` that works with SQL dumps of taxonomic databases on your own machine. https://github.com/ropensci/taxizedb It includes NCBI and actually has a `classification()` function that replicates what the same function does here. It doesn't have an equivalent for `genbank2uid` though

**Comment by afkoeppel** [comment]
Thanks so much.  I installed the new version from github.  I can pass the key to my genbank2uid() call , but my classification() call is throwing a warning about a lack of key, even though I provided it with the same API key:
No ENTREZ API key provided
See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/

The docs for genbank2uid() describe a key=NULL argument for this purpose, but not the classification() docs. Is there a different way to pass the API key to classification()?

**Comment by sckott** [comment]
See this bit in the docs https://github.com/ropensci/taxize/blob/master/R/getkey.R#L14-L36 

We recommend storing your keys as environment variables so you don't have to pass them in to each function call. 

`classification` and a few similar functions are a bit complicated as they call other functions from the pkg within them, so I felt that users can just store keys as env vars or R options and then we grab them for you - this is also more secure in case you forget to hide your api key in your public code
