### ISSUE TITLE
Give articles names

### ISSUE THREAD

**Issue by jeroen** [ropensci/taxize#772]
See pkgdown site: https://docs.ropensci.org/taxize/articles/

**Comment by Rekyt** [comment]
Hi @sckott :wave:
I think I can submit a PR dealing with that, be before I do that I have to askr is there a particular reason why all vignettes header look like this:
https://github.com/ropensci/taxize/blob/027a572ce9d8218387caac179f67c0656228c30b/vignettes/taxize_case_study.Rmd#L1-L5
Compared to "regular" vignettes with YAML header:
https://github.com/ropensci/crul/blob/1d340710303529582dec1c65e2365c13d9768d00/vignettes/async.Rmd#L1-L8

Thanks!

**Comment by sckott** [comment]
the first style is how vignettes used to be, before rmarkdown pkg arrived. its a bit complicated. 

- for cran and users that have taxize installed: don't want any failures due to bad http requests, so i'd like vignettes pre-built so that they are still useable. 
- for https://docs.ropensci.org/taxize/: its okay for the vignettes to build from scratch for this as we can try again if there's any bad requests

To do both of these, I think its easiest to just keep the source elsewhere (in `inst/vign/`), and then vignettes has pre-built versions. We could automate putting the rmarkdown style header in i guess, after moving the built vignette from inst/vign to vignettes, not tried that yet

**Comment by Rekyt** [comment]
Alright! What we've done in rromeo for the README and that could be applicable to vignettes is to have vcr cassettes to read. The cassettes could expire after a certain time for example.

**Comment by sckott** [comment]
have you had any problems on cran with vcr with vignettes? haven't tried it myself yet. 

I'd be interested to see how it looks here
