### ISSUE TITLE
getting tidy df from species list

### ISSUE THREAD

**Issue by afredstonhermann** [ropensci/taxize#779]
Thanks for developing this great resource. I have a long list of species and I'm trying to turn it into a tidy dataframe with columns for each taxonomic level, like in [this example](https://github.com/ropensci/worrms/issues/4). 

I tried following that code exactly, but it gives an error because some of the UIDs don't find a match in ITIS:
```
spplist <- c("alosa aestivalis", "alosa pseudoharengus", "alosa sapidissima", 
          "amblyraja radiata", "ammodytes dubius", "anarhichas lupus", 
          "argentina silus", "brosme brosme", "cancer borealis", "cancer irroratus", 
          "centropristis striata", "citharichthys arctifrons", "clupea harengus", 
          "crustacea shrimp", "dipturus laevis", "enchelyopus cimbrius", 
          "gadus morhua", "geryon quinquedens", "glyptocephalus cynoglossus", 
          "helicolenus dactylopterus", "hemitripterus americanus", "hippoglossoides platessoides", 
          "homarus americanus", "illex illecebrosus", "lepophidium profundorum", 
          "leucoraja erinacea", "leucoraja garmani", "leucoraja ocellata", 
          "limulus polyphemus", "loligo pealeii", "lophius americanus", 
          "macrouridae", "malacoraja senta", "melanogrammus aeglefinus", 
          "merluccius bilinearis", "mustelus canis", "myctophidae spp.", 
          "myoxocephalus octodecemspinosus", "myxine glutinosa", "paralichthys dentatus", 
          "paralichthys oblongus", "peprilus tracanthus", "peprilus triacanthus", 
          "peristedion miniatum", "phycis chesteri", "placopecten magellanicus", 
          "pollachius virens", "prionotus carolinus", "prionotus evolans", 
          "raja eglanteria", "scomber scombrus", "scophthalmus aquosus", 
          "scyliorhinus retifer", "sebastes fasciatus", "squalus acanthias", 
          "stenotomus chrysops", "tautogolabrus adspersus", "urophycis chuss", 
          "urophycis regia", "urophycis tenuis", "zenopsis conchifer", 
          "zoarces americanus")
uids <- na.omit(get_uid(spplist))
fishdf <- dplyr::tbl_df(cbind(classification(uids, db="itis")))
# Error in `$<-.data.frame`(`*tmp*`, "query", value = c("224703", "34774",  : replacement has 59 rows, data has 47
```

So I tried deleting the list entries in the output of classification() that are empty, which doesn't lead to an error, but produces a data frame that just has one column with string lists in each row: 
```
class <- classification(uids, db="itis") 
class_remove_NAs <- lapply(class, function(x) x[!is.na(x)]) 
class_distinct <- class_remove_NAs[lengths(class_remove_NAs)>0] # yields 47 entries instead of 59
fishdf2 <- dplyr::tbl_df(cbind(class_distinct)) # runs but does not produce a tidy df like in the example 
```

How can I get a tidy taxonomy dataframe from this species list?

**Comment by sckott** [comment]
thanks for your question! in the future please include your R session info (after loading taxize, so we get the taxize version)

a few things: 

- we could fail better to help users more, opened an issue for that - basically, you shouldn't mix data sources, so since you got ids from NCBI (uids), you cant query ITIS for data with NCBI ids. In your case you applied na.omit to the output of get_uid, removing the s3  class, so your call to classification did in fact try itis, but if you passed output of get_uid unaltered it would know it was from ncbi, and go to ncbi to get the classification data - anyway, we'll try to make this fail better
- did you want rbind instead of cbind above? i imagine you wanted rbind. we have rbind and cbind methods for classification output, so it tries to combine them smartly, but sometimes has trouble with ncbi since they give so many ranks as unknown/etc.
- rbind.classification should work with empty results, so you don't need to use na.omit, it removes those results before combining them. try the below:

```r
uids <- get_uid(spplist)
classes <- classification(uids)
rbind(classes)
```

**Comment by afredstonhermann** [comment]
Thanks so much for the fast reply and for explaining that the source of the problem was the database discrepancy--and sorry for forgetting session info. I didn't realize that get_uid was unique to NCBI and incompatible with other databases. Your solution works perfectly and I also just discovered that I can give Latin names directly to `classification(spplist, db="itis")` and it will work. Thanks again!

**Comment by sckott** [comment]
great, glad it works. yes, you can give names directly to `classification`. which uses `get_*` functions under the hood, so `get_` behavior applies when passing names into `classification`
