### ISSUE TITLE
get_gbifid is case senstitive

### ISSUE THREAD

**Issue by ocstringham** [ropensci/taxize#868]
I was not expecting `get_gbifid` to be case sensitive. Is this by design?

Example: `get_gbifid_("iguana")` returns no results but `get_gbifid_("Iguana")` returns the Genus Iguana.

**Comment by sckott** [comment]
Thanks for the issue. 

Its not `taxize` that's responsible for this, its GBIF

One option is to use `method = "lookup"` option, which uses the GBIF API route `/species/search` https://www.gbif.org/developer/species#searching rather than `/species/match` (the default option for `method`)

```r
get_gbifid_("iguana", method = "lookup")
```

On the GBIF website it's not case sensitive, but they must use a different API route behind the scenes, which wouldn't be surprising.

**Comment by ocstringham** [comment]
Good to know, thank you for your response.

**Comment by sckott** [comment]
Sorry I don't have a better solution. I'm sure it's frustrating. It might be easier to use `rgbif` directly, https://docs.ropensci.org/rgbif/reference/name_backbone.html or https://docs.ropensci.org/rgbif/reference/name_lookup.html  as I don't think we allow users to pass on any of the additional parameters that those API methods accept here

**Comment by ocstringham** [comment]
Thanks! No it's not bad at all. Most of my code is set up with taxize so luckily in this case all I have to do is capitalize.
