### ISSUE TITLE
Order of ranks not consistent with NCBI data

### ISSUE THREAD

**Issue by transue** [ropensci/taxize#875]
In a recent download of taxonomy data from NCBI, I checked the relative rankings of ALL species and found that two ranks listed in ./inst/ignore/rank_ref_script.R seem out of place.  Details follow...

<details>
<summary><strong>Session Info</strong></summary>
Using the ranks provided in at this site: https://github.com/ropensci/taxize/issues/835 which appear to be derived from ./inst/ignore/rank_ref_script.R , I found two ranks which appear out of order when used with the NCBI data from: https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz

1. _forma specialis_ should be MORE specific than _forma_
2. isolate should be MORE specific than strain (it was the most specific rank, in fact)

While I do not consider NCBI's ranking to be the definitive authority, I also don't know the source of the data provided here.  I imagine it is provided somewhere, but have not researched it.  I propose a couple of options to whomever considers this important:

- Confirm that the ranks in taxize are correct and contact NCBI so that they can update their ranking system
- Confirm with an authoritative source and correct taxize
- Place a note that a discrepancy was noticed and users may experience issues if assuming that ranks follow one of the two conventions.

</details>

**Comment by transue** [comment]
I am contractor at the US EPA and can be contacted using my EPA email address: transue.tom@epa.gov . Thank you for providing this code base!  --Tom

**Comment by trvinh** [comment]
Hi @transue 

I agree with you that `isolate` is more specific than `strain`, but how does it related to `morph` and `subvariety` to be the most specific rank as you mentioned? I found no connection to `morph` and `subvariety` to any other ranks but `species`. 

The same for `forma` and `formaspecialis`, they are both parents of `strain` and child of `varietas`. I found no species, where it has both `forma` and `formaspecialis` in the taxonomy hierarchy in order to specify which one is more specific than the other. Or did I miss something? Interestingly, I found 3 taxa that have `formaspecialis` twice and directly next to each other in their hierarchy strings (taxID 1142511, 299864 and 299865).

I am attaching here the graph of all available taxonomy ranks I created from the NCBI taxonomy DB file (taxdump.tar.gz, downloaded on May 14th). Could you please correct me if I war wrong. Many thanks!
![image](https://user-images.githubusercontent.com/19269760/118880561-4be7a200-b8f2-11eb-908b-357cc9ecfab4.png)

**Comment by sckott** [comment]
is this issue resolved @trvinh ?

**Comment by trvinh** [comment]
@sckott with the PR #876, yes.

**Comment by sckott** [comment]
great, thx
